---
title: "README"
author: "Su-Fang"
date: "October 25, 2015"
output: html_document
------------
### Introduction
The purpose of this project is to get experience in collecting, working with, and cleaning a data set. The goal is to prepare a tidy data that can be used for later analysis.

### Proejct scheme  
One of the most exciting areas in all of data science right now is wearable computing. Companies like Fitbit, Nike, and Jawbone Up are racing to develop the most advanced algorithms to attract new users. The data linked to the course website represent data collected from the accelerometers from the **Samsung Galaxy S smartphone**. Learn to create one R script called **run_analysis.R** that does the following:

###  
1. Merges the training and the test sets to create one data set (*MergedData*).  
2. Extracts only the measurements on the mean and standard deviation for each measurement (*SelectedData*).  
3. Uses descriptive activity names to name the activities in the data set.  
4. Appropriately labels the data set with descriptive activity names.  
5. Creates a second, independent tidy data set with the average of each variable for each activity and each subject (*MyTidyData.txt*).

### Raw and output data  
* The data link for the raw data is denoted in *CodeBook.md*.
* *run_analysus.R* was compiled in RStudio (Version 0.99.467).
* One copy of *MyTidyData.txt* was uploaded into the same Repo.


